# VANT-Agent Quick Installer
# Standalone PowerShell installer (no Inno Setup required)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path $PSScriptRoot -Parent
$DistDir = Join-Path $ScriptDir "dist"
$AgentExe = Join-Path $DistDir "VANT-Agent.exe"
$InstallerOutDir = Join-Path $DistDir "installer"

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  VANT-Agent Installer" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# Check executable exists
if (-not (Test-Path $AgentExe)) {
    Write-Host "[!] Building VANT-Agent.exe first..." -ForegroundColor Yellow
    & "$PSScriptRoot\build_installer.ps1"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[x] Build failed" -ForegroundColor Red
        exit 1
    }
}

$SizeMB = [math]::Round((Get-Item $AgentExe).Length / 1MB, 1)
Write-Host "[+] VANT-Agent.exe ready ($SizeMB MB)" -ForegroundColor Green
Write-Host ""

# --- Interactive prompts ---
$DefaultUrl = "https://192.168.12.43"

Write-Host "Server Configuration:" -ForegroundColor Yellow
Write-Host "  Enter VANT-SIEM server URL (Nginx reverse proxy):" -ForegroundColor Gray
$ServerUrl = Read-Host "  [$DefaultUrl]"
if ([string]::IsNullOrWhiteSpace($ServerUrl)) { $ServerUrl = $DefaultUrl }
$ServerUrl = $ServerUrl.TrimEnd('/')

# Install location
$DefaultInstallDir = "$env:ProgramFiles\VANT-Agent"
Write-Host "  Enter install directory:" -ForegroundColor Gray
$InstallDir = Read-Host "  [$DefaultInstallDir]"
if ([string]::IsNullOrWhiteSpace($InstallDir)) { $InstallDir = $DefaultInstallDir }

Write-Host ""
Write-Host "[1/5] Installing to: $InstallDir" -ForegroundColor Yellow

# Create directory
if (-not (Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}

# Copy files
Write-Host "[2/5] Copying agent executable..." -ForegroundColor Yellow
Copy-Item -Path $AgentExe -Destination "$InstallDir\VANT-Agent.exe" -Force

# Generate config.yaml
Write-Host "[3/5] Generating config.yaml..." -ForegroundColor Yellow
$isHttps = $ServerUrl.StartsWith("https")
$configContent = @"
# VANT-SIEM Agent Configuration
# Generated by installer on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

agent:
  id: "agent-windows"
  host_name: "$env:COMPUTERNAME"
  interval_seconds: 10

output:
  endpoint: "$ServerUrl/logs/api/ingest/bulk/"
  source_endpoint: "$ServerUrl/logs/api/sources/"
  timeout_seconds: 10
  auth:
    mode: "none"
    username: ""
    password: ""
    token: ""
  tls:
    enabled: false
    verify: false
    ca_cert: ""

control:
  server_url: "$ServerUrl"
  require_https: $isHttps
  token: ""
  poll_seconds: 30
  verify_ssl: false
  inventory_seconds: 86400
  dlp_poll_seconds: 60
  dlp_scan_seconds: 30

asset_audit:
  enabled: true

aegis_dlp:
  enabled: true
  max_file_size_mb: 25
  max_files_per_scan: 12000
  max_scan_seconds: 20
  scan_paths: []
  monitored_extensions:
    - ".txt"
    - ".log"
    - ".csv"
    - ".json"
    - ".xml"
    - ".md"
    - ".doc"
    - ".docx"
    - ".docm"
    - ".rtf"
    - ".xls"
    - ".xlsx"
    - ".xlsm"
    - ".ppt"
    - ".pptx"
    - ".pptm"
    - ".pdf"
    - ".ps1"
    - ".bat"
    - ".cmd"
    - ".sql"
    - ".env"
    - ".properties"
    - ".html"
    - ".htm"
    - ".conf"
    - ".ini"
    - ".odt"
    - ".ods"
    - ".odp"

collectors:
  windows_eventlog:
    enabled: true
    channels:
      - "Application"
      - "Security"
      - "System"
"@

$configPath = Join-Path $InstallDir "config.yaml"
$configContent | Out-File -FilePath $configPath -Encoding utf8

# Create logs directory
$logDir = Join-Path $InstallDir "logs"
if (-not (Test-Path $logDir)) {
    New-Item -ItemType Directory -Path $logDir | Out-Null
}

# Copy requirements.txt if exists
$reqFile = Join-Path $ScriptDir "requirements.txt"
if (Test-Path $reqFile) {
    Copy-Item -Path $reqFile -Destination "$InstallDir\requirements.txt" -Force
}

Write-Host "[4/5] Creating state directory..." -ForegroundColor Yellow
$stateDir = Join-Path $InstallDir ".vant_state"
if (-not (Test-Path $stateDir)) {
    New-Item -ItemType Directory -Path $stateDir | Out-Null
}

# Create desktop shortcut
Write-Host "[5/5] Creating shortcuts..." -ForegroundColor Yellow
$WScriptShell = New-Object -ComObject WScript.Shell
$DesktopPath = [Environment]::GetFolderPath("Desktop")
$Shortcut = $WScriptShell.CreateShortcut("$DesktopPath\VANT-Agent.lnk")
$Shortcut.TargetPath = "$InstallDir\VANT-Agent.exe"
$Shortcut.WorkingDirectory = $InstallDir
$Shortcut.Description = "VANT-SIEM Agent v1.1.0"
$Shortcut.Save()

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  Installation Complete!" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Installed to: $InstallDir" -ForegroundColor White
Write-Host "  Config: $configPath" -ForegroundColor White
Write-Host "  Desktop shortcut created" -ForegroundColor White
Write-Host ""
Write-Host "  To run: Start -> VANT-Agent or double-click desktop shortcut" -ForegroundColor Gray
Write-Host ""

# Ask if user wants to launch
$launch = Read-Host "Launch agent now? (y/n)"
if ($launch -eq "y" -or $launch -eq "Y") {
    Write-Host ""
    Write-Host "[>] Starting VANT-Agent..." -ForegroundColor Green
    Start-Process -FilePath "$InstallDir\VANT-Agent.exe" -ArgumentList "--config", "`"$configPath`"" -WindowStyle Normal
}
